galaxy_info:
  role_name: nginx
  description: Установка и настройка на сервере с Ubuntu Nginx
  author: Andrey Novikov
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: Ubuntu
      versions:
        - all