galaxy_info:
  role_name: deploy
  description: Установка и настройка на серверах Zabbix-agent
  author: Andrey Novikov
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: Ubuntu
      versions:
        - all
    - name: CentOS
      versions:
        - all