galaxy_info:
  role_name: elk-kibana
  description: Установка и настройка на сервере с Ubuntu Elasticsearch и Kibana
  author: Andrey Novikov
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: Ubuntu
      versions:
        - all