galaxy_info:
  role_name: bind
  description: Установка и настройка на MAIN сервере с Ubuntu Bind9
  author: Andrey Novikov
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: Ubuntu
      versions:
        - all