galaxy_info:
  role_name: postgresql
  description: Установка и настройка на сервере с CentOS PostgreSQL-12
  author: Andrey Novikov
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: CentOS
      versions:
        - all