galaxy_info:
  role_name: apache
  description: Установка и настройка на сервере с Ubuntu Apache2
  author: Andrey Novikov
  license: MIT
  min_ansible_version: 2.9
  platforms: 
    - name: Ubuntu
      versions:
        - all